### ISSUE TITLE
Not able to get jars.

### ISSUE THREAD

**Issue by vikash09** [Redpill-Linpro/alfresco-systemmessages#11]
As explained in readme.md , I added dependencies in pom.xml
And got error jar is not available. 
I am using sdk 2.2.0

**Comment by buimichael** [comment]
Did you add our public maven repository to your pom file?

If that still doesn't work you can manually download the jar files from our nexus: https://maven.redpill-linpro.com/nexus/index.html#nexus-search;quick~alfresco-systemmessages

**Comment by vikash09** [comment]
Thank you very much , Sorry for that , I forgot to add repository
<repositories>
<repository>
<id>redpill-public</id>
<url>
https://maven.redpill-linpro.com/nexus/content/groups/public
</url>
</repository>
</repositories>
