### ISSUE TITLE
Maven build not working

### ISSUE THREAD

**Issue by ESWBitto** [Redpill-Linpro/alfresco-systemmessages#12]
Hello,

So what I did was downloaded the code and then put it into my server that has maven installed. The only thing that I did was run mvn clean install and got the jar files for both the repo and the share. I placed them in /tomcat/shared/lib and restarted alfresco service.

When I do that share will not load. I'm running 5.1 CE. Is there a way to build this so that I can run it as an amp? I still don't know why share is not accessible after adding the jar files.

**Comment by billerby** [comment]
Do you have any output from the share.log file?

**Comment by billerby** [comment]
@ESWBitto  After testing seems to be a classloading issue, if you put the repo-jar in alfresco/WEB-INF/lib and the share-jar in share/WEB-INF/lib it works.

**Comment by ESWBitto** [comment]
Yup, that works! Now I need to package it as an amp. Any pointers in the SDK?
