### ISSUE TITLE
Use popups for messages

### ISSUE THREAD

**Issue by magp3** [Redpill-Linpro/alfresco-systemmessages#2]

**Comment by CesarCapillas** [comment]
+1

**Comment by rootinshell** [comment]
+1

**Comment by mrgrechkinn** [comment]
@CesarCapillas @magp3 @rootinshell 
How do you see this? What about "high" priority it's should't hided according to the idea of the author.

**Comment by billerby** [comment]
Well I think popups is a bad idea.
-1 from me :)

**Comment by buimichael** [comment]
I think the idea of using popup is because with the current implementation it sometimes pushes some components in the client further down making it look weird in some pages. Can't remember where that occurs, but I remember @magp3 talked about it.
