### ISSUE TITLE
Can't delete a system message from UI

### ISSUE THREAD

**Issue by CesarCapillas** [Redpill-Linpro/alfresco-systemmessages#4]
Hi,

First of all, thanks for the addon, it is really useful. I found a minor problem:

When I delete a system message I get an 404 exception in Alfresco 5.0.25 EE and Alfresco 5.1.g such as:

`DELETE http://localhost:8080/share/proxy/alfresco/api/node/workspace/SpacesStore/eabab72c-68e6-4c91-bf3a-7d13343daa44 404 (Not found)
`

I think this webscript does not exist for "workspace". On the other way, I can confirm the uuid and also I can delete datalists from /Data Dictionary/datalists/system-messages-datalist with no problems.

Regards.

--C.

**Comment by magp3** [comment]
@CesarCapillas Thanks for reporting! The webscript used exists in 4.2.5.1 but seems to have been removed. I pushed a fix to the develop branch, tested on 5.1.1 EE.
