### ISSUE TITLE
System messages are not showed on Aikau pages (Alfresco 5.1.x, 5.2)

### ISSUE THREAD

**Issue by ikaygorodov** [Redpill-Linpro/alfresco-systemmessages#7]
System messages does not work for Aikau based pages.
For example /share/page/dp/ws/faceted-search.

**Comment by billerby** [comment]
Thanks for the info. Its totally untested on 5.x-versions of Alfresco, I will look into this.

**Comment by seky739** [comment]
for me it works on Alfresco CE 5.1

**Comment by rootinshell** [comment]
any help for using it with alfresco 5.2  i tried downloading : 
_alfresco-systemmessages-share-1.1.0-20170331.074834-4.jar_
_alfresco-systemmessages-repo-1.1.0-20170331.074832-4.jar_ 
unfortunately when i put them into /tomcat/share/lib i receive an error 404 when accessing the share, could  someone please clarify the build process for a beginner ? 

Regards.

**Comment by seky739** [comment]
You must build it from source using mvn install and then you can put it in two locations. If i try put it first in  /tomcat/share/lib isn't working. But if you put repo.jar to /tomcat/webapps/alfresco/WEB-INF/lib and share.jar to /tomcat/webapps/share/WEB-INF/lib it start work. Try it.

Regards Seky

**Comment by billerby** [comment]
Now (v1.2.0) working on Aikau pages as well.
