### ISSUE TITLE
Adding groups in a site down

### ISSUE THREAD

**Issue by H0lyve** [Redpill-Linpro/alfresco-systemmessages#9]
Hello,

First, I have to let you know that I'm a fairly new at Alfresco.
I installed this module on a freshly install Alfresco Entreprise 5.2.1 and it work fine. Sadly it also ruins the group adding function. In the interface of any site, if I try to add a groups to it, I select one, but when I click on the Add >> button, the "2 Add these Groups" stays empty. 
Nb: the javascript console says : 
add-groups:173 Uncaught TypeError: Alfresco.GroupsList is not a constructor
    at add-groups:173
(anonymous) @ add-groups:173

There is a probably useless screenshot :
![capture](https://user-images.githubusercontent.com/16069817/30280885-32f7a940-9711-11e7-8cb0-5c2767174583.PNG)

Yet, thanks you for that module and thanks you in advance for your help.

**Comment by vojtechm** [comment]
Hi, I'm also facing this unfortunate issue in this great module. Is there any way to fix this?

**Comment by billerby** [comment]
Thanks!

Sadly I have no time to investigate this at the moment, but feel free to fix it and issue a pull request.

**Comment by ghost** [comment]
Hi,

Adding group="template-common" to the extension markup like <@link> and <@script> solves the issue. e.g

in org.redpill.global.alfresco.components.head.resources.get.html.ftl  replace the lines with below lines

<@markup id="systemmessages-alfrescoResources" action="after" target="alfrescoResources" scope="global">
   <@link href="${url.context}/res/redpill/components/global/notifications.css" group="template-common" />
   <@script type="text/javascript" src="${url.context}/res/yui/cookie/cookie.js" group="template-common" />
   <@script type="text/javascript" src="${url.context}/res/redpill/components/global/notifications.js" group="template-common"></@script>
</@>

Though I would like to know from the author two things for my understanding.

1. Why other pages are not getting affected when the group is not added ?
2. What is the use of group in the markup definition ?

**Comment by billerby** [comment]
@rastoh thanks for the code! I will try to review it soon and commit it to our codebase. 

Your questions are relevant and interesting :) I have no straight answer now without digging into the surf-framework.

**Comment by billerby** [comment]
Fixed in 1.2.0-SNAPSHOT build. Thanks @rastoh
